"""Feature archetypes and operating rules used by permit approvals."""

from __future__ import annotations

from ..models import *

FEATURE_ARCHETYPES: dict[str, FeatureArchetype] = {
    "arterial_road": FeatureArchetype(
        "arterial_road",
        "Arterial Road",
        "infrastructure",
        "LINE",
        service_type="mobility",
        coverage_radius_m=140,
        capacity=2,
        land_use="transport_corridor",
        coverage_effects={"activity": 1, "services": 1},
        network_type="mobility",
        network_strength=2,
        allowed_district_types=("mercantile", "civic", "industrial", "academic"),
        conflict_district_types=("natural",),
        display_state="road",
    ),
    "utility_backbone": FeatureArchetype(
        "utility_backbone",
        "Utility Backbone",
        "infrastructure",
        "LINE",
        service_type="utilities",
        coverage_radius_m=140,
        capacity=3,
        land_use="utility_corridor",
        coverage_effects={"exposure": -1, "services": 2},
        network_type="utilities",
        network_strength=3,
        mitigation_effects={"flood": 1, "fire": 1},
        allowed_district_types=("industrial", "civic", "mercantile", "residential"),
        conflict_district_types=("natural",),
        display_state="utility",
    ),
    "neighborhood_park": FeatureArchetype(
        "neighborhood_park",
        "Neighborhood Park",
        "natural_resource",
        "POLYGON",
        service_type="green_buffer",
        coverage_radius_m=90,
        capacity=2,
        land_use="neighborhood_park",
        coverage_effects={"trust": 1, "exposure": -1, "services": 1},
        network_type="green_buffer",
        network_strength=1,
        mitigation_effects={"heat": 1, "noise": 1},
        allowed_district_types=("residential", "natural", "academic", "civic"),
        conflict_district_types=("industrial",),
        display_state="park",
    ),
    "local_street_hint": FeatureArchetype(
        "local_street_hint",
        "Local Street Hint",
        "infrastructure",
        "LINE",
        coverage_radius_m=40,
        land_use="local_street",
        display_state="road",
    ),
    "residential_block": FeatureArchetype(
        "residential_block",
        "Residential Block",
        "land_use",
        "POLYGON",
        capacity=0,
        land_use="housing",
        allowed_district_types=("residential", "mercantile"),
        display_state="housing",
    ),
    "commercial_block": FeatureArchetype(
        "commercial_block",
        "Commercial Block",
        "land_use",
        "POLYGON",
        capacity=0,
        land_use="commerce",
        allowed_district_types=("mercantile", "civic", "residential"),
        display_state="commerce",
    ),
    "civic_building": FeatureArchetype(
        "civic_building",
        "Civic Building",
        "public_resource",
        "POINT",
        capacity=0,
        land_use="civic",
        allowed_district_types=("civic", "residential", "academic"),
        display_state="civic",
    ),
    "industrial_yard": FeatureArchetype(
        "industrial_yard",
        "Industrial Yard",
        "land_use",
        "POLYGON",
        capacity=0,
        land_use="industry",
        allowed_district_types=("industrial",),
        display_state="industry",
    ),
    "academic_block": FeatureArchetype(
        "academic_block",
        "Academic Block",
        "public_resource",
        "POLYGON",
        capacity=0,
        land_use="campus",
        allowed_district_types=("academic", "civic"),
        display_state="campus",
    ),
    "natural_patch": FeatureArchetype(
        "natural_patch",
        "Natural Patch",
        "natural_resource",
        "POLYGON",
        capacity=0,
        land_use="open_space",
        allowed_district_types=("natural", "residential", "academic"),
        display_state="park",
    ),
    "connector_corridor": FeatureArchetype(
        "connector_corridor",
        "Connector Corridor",
        "infrastructure",
        "LINE",
        service_type="mobility",
        coverage_radius_m=150,
        capacity=2,
        land_use="transport_corridor",
        coverage_effects={"activity": 1, "exposure": -1, "services": 1},
        network_type="mobility",
        network_strength=2,
        allowed_district_types=("mercantile", "civic", "industrial"),
        conflict_district_types=("natural", "residential"),
    ),
    "licensed_procession": FeatureArchetype(
        "licensed_procession",
        "Licensed Procession",
        "event",
        "LINE",
        service_type="culture_access",
        coverage_radius_m=110,
        capacity=1,
        land_use="temporary_event_route",
        coverage_effects={"trust": 1, "friction": 1},
        allowed_district_types=("civic", "academic", "mercantile"),
        conflict_district_types=("industrial", "natural"),
        incident_type="crowd_control",
        display_state="temporary",
    ),
    "utility_trench": FeatureArchetype(
        "utility_trench",
        "Utility Trench",
        "infrastructure",
        "LINE",
        service_type="utilities",
        coverage_radius_m=125,
        capacity=3,
        land_use="utility_corridor",
        coverage_effects={"exposure": -1, "services": 3},
        network_type="utilities",
        network_strength=3,
        mitigation_effects={"flood": 1, "fire": 1},
        allowed_district_types=("industrial", "civic", "mercantile"),
        conflict_district_types=("natural", "residential"),
    ),
    "protected_reserve": FeatureArchetype(
        "protected_reserve",
        "Protected Reserve",
        "natural_resource",
        "POLYGON",
        service_type="green_buffer",
        coverage_radius_m=90,
        capacity=3,
        land_use="protected_reserve",
        coverage_effects={"trust": 1, "exposure": -1, "services": 1},
        network_type="green_buffer",
        network_strength=2,
        mitigation_effects={"heat": 1, "noise": 1, "ecology": 1},
        allowed_district_types=("natural", "academic"),
        conflict_district_types=("industrial", "mercantile"),
    ),
    "mixed_use_overlay": FeatureArchetype(
        "mixed_use_overlay",
        "Mixed-Use Overlay",
        "land_use",
        "POLYGON",
        coverage_radius_m=100,
        land_use="mixed_use",
        coverage_effects={"activity": 1, "friction": 1},
        allowed_district_types=("residential", "mercantile"),
        conflict_district_types=("natural", "civic"),
        display_state="overlay",
    ),
    "child_service_annex": FeatureArchetype(
        "child_service_annex",
        "Child Service Annex",
        "public_resource",
        "POINT",
        service_type="child_services",
        coverage_radius_m=125,
        capacity=4,
        land_use="civic_service",
        coverage_effects={"trust": 1, "exposure": -1, "services": 4},
        network_type="green_buffer",
        network_strength=1,
        allowed_district_types=("residential", "academic", "civic"),
        conflict_district_types=("industrial",),
    ),
    "vendor_market": FeatureArchetype(
        "vendor_market",
        "Vendor Market",
        "business",
        "POINT",
        service_type="culture_access",
        coverage_radius_m=100,
        capacity=2,
        land_use="commerce",
        coverage_effects={"activity": 1, "trust": 1, "services": 1},
        allowed_district_types=("mercantile", "residential"),
        conflict_district_types=("civic", "natural"),
        incident_type="sanitation",
    ),
    "renovation_site": FeatureArchetype(
        "renovation_site",
        "Renovation Site",
        "land_use",
        "POINT",
        coverage_radius_m=80,
        land_use="residential_renewal",
        coverage_effects={"activity": 1},
        allowed_district_types=("residential", "mercantile"),
        conflict_district_types=("natural", "academic"),
        incident_type="inspection",
    ),
    "fire_coverage_area": FeatureArchetype(
        "fire_coverage_area",
        "Fire Coverage Area",
        "public_resource",
        "POLYGON",
        service_type="fire_response",
        coverage_radius_m=160,
        capacity=5,
        land_use="public_safety",
        coverage_effects={"exposure": -3, "services": 3},
        network_type="fire_response",
        network_strength=5,
        mitigation_effects={"fire": 2},
        allowed_district_types=("industrial", "civic", "residential"),
        conflict_district_types=("natural",),
    ),
    "museum_grant_site": FeatureArchetype(
        "museum_grant_site",
        "Museum Grant Site",
        "public_resource",
        "POINT",
        service_type="culture_access",
        coverage_radius_m=130,
        capacity=3,
        land_use="cultural",
        coverage_effects={"trust": 2, "services": 1},
        allowed_district_types=("civic", "academic", "mercantile"),
        conflict_district_types=("industrial",),
    ),
    "compliance_case": FeatureArchetype(
        "compliance_case",
        "Compliance Case",
        "compliance",
        "POINT",
        coverage_radius_m=75,
        land_use="compliance_case",
        coverage_effects={"friction": 1},
        incident_type="noncompliance",
        display_state="case",
    ),
    "civic_incident_marker": FeatureArchetype(
        "civic_incident_marker",
        "Civic Incident Marker",
        "incident",
        "POINT",
        coverage_radius_m=75,
        land_use="incident_file",
        coverage_effects={"friction": -1, "exposure": -1},
        incident_type="civic_grievance",
        display_state="incident",
    ),
    "bus_priority_link": FeatureArchetype(
        "bus_priority_link",
        "Bus Priority Link",
        "infrastructure",
        "LINE",
        service_type="mobility",
        coverage_radius_m=150,
        capacity=3,
        land_use="bus_priority",
        coverage_effects={"activity": 1, "services": 1},
        network_type="mobility",
        network_strength=3,
        allowed_district_types=("mercantile", "civic", "academic", "industrial"),
        conflict_district_types=("natural",),
    ),
    "water_main_loop": FeatureArchetype(
        "water_main_loop",
        "Water Main Loop",
        "infrastructure",
        "LINE",
        service_type="utilities",
        coverage_radius_m=150,
        capacity=3,
        land_use="water_loop",
        coverage_effects={"exposure": -2, "services": 3},
        network_type="utilities",
        network_strength=3,
        mitigation_effects={"flood": 1, "fire": 1},
        allowed_district_types=("industrial", "civic", "residential", "mercantile"),
        conflict_district_types=("natural",),
    ),
    "green_buffer_reserve": FeatureArchetype(
        "green_buffer_reserve",
        "Green Buffer Reserve",
        "natural_resource",
        "POLYGON",
        service_type="green_buffer",
        coverage_radius_m=120,
        capacity=3,
        land_use="green_buffer",
        coverage_effects={"trust": 1, "exposure": -2, "services": 1},
        network_type="green_buffer",
        network_strength=3,
        mitigation_effects={"heat": 2, "noise": 1, "ecology": 2},
        allowed_district_types=("natural", "residential", "academic"),
        conflict_district_types=("industrial",),
    ),
    "inspection_order": FeatureArchetype(
        "inspection_order",
        "Inspection Order",
        "compliance",
        "POINT",
        coverage_radius_m=75,
        capacity=1,
        land_use="inspection_order",
        coverage_effects={"exposure": -1, "friction": 1},
        mitigation_effects={"pollution": 1, "fire": 1, "noise": 1},
        incident_type="inspection",
        display_state="case",
    ),
    "affordable_infill_rezoning": FeatureArchetype(
        "affordable_infill_rezoning",
        "Affordable Infill Rezoning",
        "land_use",
        "POLYGON",
        coverage_radius_m=100,
        capacity=1,
        land_use="affordable_infill",
        coverage_effects={"activity": 1, "friction": 1},
        housing_effects={"affordability": 4},
        starts_chain_id="affordable_infill_buildout",
        allowed_district_types=("residential", "mercantile"),
        conflict_district_types=("natural", "industrial"),
        display_state="overlay",
    ),
    "construction_site": FeatureArchetype(
        "construction_site",
        "Construction Site",
        "land_use",
        "POINT",
        coverage_radius_m=90,
        capacity=1,
        land_use="construction_site",
        coverage_effects={"activity": 1, "friction": 1, "exposure": 1},
        hazard_effects={"noise": 1, "fire": 1},
        allowed_district_types=("residential", "mercantile", "industrial"),
        conflict_district_types=("natural",),
        incident_type="construction",
        display_state="temporary",
    ),
    "occupancy_certificate": FeatureArchetype(
        "occupancy_certificate",
        "Occupancy Certificate",
        "compliance",
        "POINT",
        service_type="utilities",
        coverage_radius_m=80,
        capacity=1,
        land_use="occupied_infill",
        coverage_effects={"activity": 1, "services": -1},
        housing_effects={"housing_capacity": 420, "population": 180, "affordability": 6},
        allowed_district_types=("residential", "mercantile"),
        conflict_district_types=("natural",),
        display_state="active",
    ),
    "vendor_sanitation_complaint": FeatureArchetype(
        "vendor_sanitation_complaint",
        "Vendor Sanitation Complaint",
        "incident",
        "POINT",
        coverage_radius_m=75,
        capacity=1,
        land_use="sanitation_complaint",
        coverage_effects={"friction": -1, "exposure": -1},
        hazard_effects={"pollution": 1, "noise": 1},
        incident_type="sanitation",
        display_state="incident",
    ),
    "license_fee_counter": FeatureArchetype(
        "license_fee_counter",
        "License Fee Counter",
        "business",
        "POINT",
        coverage_radius_m=70,
        capacity=1,
        land_use="commerce",
        coverage_effects={"activity": 1},
        allowed_district_types=("mercantile", "civic", "industrial"),
        conflict_district_types=("natural",),
        display_state="case",
    ),
    "settlement_agreement": FeatureArchetype(
        "settlement_agreement",
        "Compliance Settlement Agreement",
        "compliance",
        "POINT",
        coverage_radius_m=75,
        capacity=1,
        land_use="settlement_case",
        coverage_effects={"exposure": -1, "friction": -1},
        allowed_district_types=("mercantile", "industrial", "residential"),
        incident_type="noncompliance",
        display_state="case",
    ),
}


HAZARD_RULES: dict[str, HazardRule] = {
    "pollution": HazardRule(
        "pollution",
        ("families", "elders", "workers", "renters", "conservationists"),
        source_effects={"industrial": 1, "business": 1},
        mitigation_service_types={"utilities": 1},
    ),
    "flood": HazardRule(
        "flood",
        ("families", "elders", "homeowners", "workers"),
        source_effects={"natural": 1},
        mitigation_service_types={"utilities": 1, "green_buffer": 1},
    ),
    "fire": HazardRule(
        "fire",
        ("families", "elders", "workers", "civil_servants"),
        source_effects={"industrial": 1, "land_use": 1},
        mitigation_service_types={"fire_response": 2, "utilities": 1},
    ),
    "noise": HazardRule(
        "noise",
        ("elders", "homeowners", "students", "artists", "families"),
        exposure_threshold=3,
        source_effects={"event": 1, "business": 1, "land_use": 1},
        mitigation_service_types={"green_buffer": 1},
    ),
    "heat": HazardRule(
        "heat",
        ("elders", "families", "workers", "renters"),
        source_effects={"industrial": 1},
        mitigation_service_types={"green_buffer": 2},
    ),
    "ecology": HazardRule(
        "ecology",
        ("conservationists", "artists", "elders", "families"),
        source_effects={"development": 1, "industrial": 1},
        mitigation_service_types={"green_buffer": 2},
    ),
}


PROJECT_CHAINS: dict[str, ProjectChainTemplate] = {
    "affordable_infill_buildout": ProjectChainTemplate(
        "affordable_infill_buildout",
        "Affordable Infill Buildout",
        "rezoning",
        (
            ProjectStepTemplate("rezoning", "Rezoning Approval", "affordable_infill_rezoning", due_after=1, next_step_id="construction", stakeholder="housing_authority"),
            ProjectStepTemplate("construction", "Construction Mobilization", "infill_construction_site", due_after=1, next_step_id="inspection", failure_step_id="inspection", stakeholder="housing_authority"),
            ProjectStepTemplate("inspection", "Final Inspection", "infill_inspection_order", due_after=1, next_step_id="occupancy", status_on_failure="delayed", stakeholder="compliance_office"),
            ProjectStepTemplate("occupancy", "Occupancy Certificate", "occupancy_certificate", due_after=1, status_on_approval="settled", stakeholder="housing_authority"),
        ),
    ),
    "vendor_compliance_chain": ProjectChainTemplate(
        "vendor_compliance_chain",
        "Vendor Complaint Escalation",
        "vendor_complaint",
        (
            ProjectStepTemplate("vendor_complaint", "Sanitation Complaint", "vendor_sanitation_complaint", due_after=1, next_step_id="vendor_enforcement", stakeholder="public_health"),
            ProjectStepTemplate("vendor_enforcement", "Vendor Enforcement", ENFORCEMENT_TEMPLATE_ID, due_after=1, status_on_approval="settled", stakeholder="public_health"),
        ),
    ),
}


SCENARIO_RULES: dict[str, ScenarioRule] = {
    "default": ScenarioRule(
        "default",
        "Default Audit",
        score_weights={"activity": 1, "trust": 1, "friction": -1, "exposure": -1, "money": 1},
        audit_priorities=("activity", "trust", "friction", "exposure"),
    ),
    "housing_mandate": ScenarioRule(
        "housing_mandate",
        "Housing Mandate",
        starting_city_effects={"activity": -2, "friction": 3},
        starting_district_effects={"housing_capacity": 180, "affordability": -4},
        docket_priority=("affordable_infill_rezoning", "water_main_loop", "child_development_park_annex"),
        score_weights={"activity": 1, "trust": 1, "friction": -1, "exposure": -1, "money": 1, "housing_capacity": 1, "affordability": 2, "vacancy_rate": 1, "displacement": -3, "renter_dissatisfaction": -2},
        audit_priorities=("capacity", "affordability", "vacancy", "displacement", "renters"),
        housing_bias={"housing_capacity": 180, "affordability": -4},
    ),
    "port_boom": ScenarioRule(
        "port_boom",
        "Port Boom",
        starting_city_effects={"activity": 5, "exposure": 3},
        starting_district_effects={"activity": 2},
        docket_priority=("water_main_loop", "bus_priority_link", "utility_expansion_trench"),
        score_weights={"activity": 2, "trust": 1, "friction": -1, "exposure": -1, "money": 1, "mobility": 1, "pollution": -3, "ecology": -2},
        audit_priorities=("activity", "mobility", "pollution", "ecology"),
        hazard_bias={"pollution": 1, "ecology": 1},
    ),
    "garden_city": ScenarioRule(
        "garden_city",
        "Garden City",
        starting_city_effects={"trust": 3, "activity": -1},
        docket_priority=("green_buffer_reserve", "natural_reserve_conversion", "child_development_park_annex"),
        score_weights={"activity": 1, "trust": 2, "friction": -1, "exposure": -1, "money": 1, "green_buffer": 2, "heat": -2, "ecology": -2, "displacement": -2},
        audit_priorities=("green buffer", "heat", "ecology", "displacement"),
        hazard_bias={"heat": -1, "ecology": -1},
    ),
}


ARCHETYPE_BASE_MIX = {
    "residential": {"families": 3, "homeowners": 2, "renters": 2, "elders": 1, "commuters": 1},
    "mercantile": {"vendors": 3, "workers": 2, "commuters": 2, "renters": 1, "artists": 1},
    "industrial": {"workers": 3, "commuters": 2, "civil_servants": 1, "renters": 1, "developers": 1},
    "civic": {"civil_servants": 3, "commuters": 2, "elders": 1, "families": 1, "workers": 1},
    "academic": {"students": 3, "artists": 2, "commuters": 1, "renters": 1, "workers": 1},
    "natural": {"conservationists": 3, "elders": 1, "artists": 1, "commuters": 1, "families": 1},
}

PRESSURE_DRIFT_GROUPS = {
    "residential": ("families", "renters"),
    "mercantile": ("workers", "vendors"),
    "industrial": ("workers", "commuters"),
    "civic": ("civil_servants", "commuters"),
    "academic": ("students", "artists"),
    "natural": ("conservationists", "artists"),
}

INCIDENT_STATE_BY_GROUP = {
    "workers": "strike",
    "civil_servants": "strike",
    "vendors": "noncompliance",
    "developers": "noncompliance",
    "homeowners": "petition",
    "elders": "complaints",
    "commuters": "complaints",
}

FEATURE_OPERATING_RULES: dict[str, FeatureOperatingRule] = {
    "arterial_road": FeatureOperatingRule("arterial_road", revenue_per_turn=1, upkeep_per_turn=1, decay_per_turn=1, maintenance_interval=6, maintenance_cost=6, repair_amount=35, failure_effects={"activity": -1, "friction": 1}),
    "utility_backbone": FeatureOperatingRule("utility_backbone", upkeep_per_turn=2, decay_per_turn=1, maintenance_interval=6, maintenance_cost=8, repair_amount=45, failure_effects={"exposure": 3, "friction": 1}),
    "neighborhood_park": FeatureOperatingRule("neighborhood_park", upkeep_per_turn=1, decay_per_turn=1, maintenance_interval=6, maintenance_cost=5, repair_amount=30, failure_effects={"exposure": 1, "trust": -1}),
    "local_street_hint": FeatureOperatingRule("local_street_hint"),
    "residential_block": FeatureOperatingRule("residential_block"),
    "commercial_block": FeatureOperatingRule("commercial_block"),
    "civic_building": FeatureOperatingRule("civic_building"),
    "industrial_yard": FeatureOperatingRule("industrial_yard"),
    "academic_block": FeatureOperatingRule("academic_block"),
    "natural_patch": FeatureOperatingRule("natural_patch"),
    "connector_corridor": FeatureOperatingRule("connector_corridor", revenue_per_turn=1, upkeep_per_turn=3, decay_per_turn=4, maintenance_interval=5, maintenance_cost=9, repair_amount=45, failure_effects={"exposure": 4, "friction": 2}),
    "licensed_procession": FeatureOperatingRule("licensed_procession", revenue_per_turn=2, upkeep_per_turn=1, lifespan_turns=1, decay_per_turn=100, failure_effects={"friction": 2, "exposure": 1}),
    "utility_trench": FeatureOperatingRule("utility_trench", upkeep_per_turn=4, decay_per_turn=5, maintenance_interval=5, maintenance_cost=10, repair_amount=50, failure_effects={"exposure": 5, "friction": 2}),
    "protected_reserve": FeatureOperatingRule("protected_reserve", revenue_per_turn=1, upkeep_per_turn=1, decay_per_turn=2, maintenance_interval=6, maintenance_cost=5, repair_amount=40, failure_effects={"exposure": 3, "trust": -2}),
    "mixed_use_overlay": FeatureOperatingRule("mixed_use_overlay", revenue_per_turn=5, upkeep_per_turn=1, decay_per_turn=1, maintenance_interval=6, maintenance_cost=7, repair_amount=35, failure_effects={"activity": -3, "friction": 2}),
    "child_service_annex": FeatureOperatingRule("child_service_annex", upkeep_per_turn=4, decay_per_turn=3, maintenance_interval=6, maintenance_cost=8, repair_amount=55, failure_effects={"exposure": 4, "friction": 2, "trust": -2}),
    "vendor_market": FeatureOperatingRule("vendor_market", revenue_per_turn=4, upkeep_per_turn=1, decay_per_turn=5, maintenance_interval=2, maintenance_cost=5, repair_amount=35, failure_effects={"friction": 3, "exposure": 2, "activity": -1}),
    "renovation_site": FeatureOperatingRule("renovation_site", revenue_per_turn=3, lifespan_turns=3, decay_per_turn=15, failure_effects={"exposure": 3, "friction": 1}),
    "fire_coverage_area": FeatureOperatingRule("fire_coverage_area", upkeep_per_turn=5, decay_per_turn=3, maintenance_interval=6, maintenance_cost=12, repair_amount=55, failure_effects={"exposure": 6, "friction": 2}),
    "museum_grant_site": FeatureOperatingRule("museum_grant_site", revenue_per_turn=2, upkeep_per_turn=2, decay_per_turn=2, maintenance_interval=6, maintenance_cost=7, repair_amount=40, failure_effects={"trust": -3, "friction": 2}),
    "compliance_case": FeatureOperatingRule("compliance_case", upkeep_per_turn=1, lifespan_turns=2, decay_per_turn=20, failure_effects={"friction": 2}),
    "civic_incident_marker": FeatureOperatingRule("civic_incident_marker", upkeep_per_turn=1, lifespan_turns=2, decay_per_turn=20, failure_effects={"friction": 2, "exposure": 1}),
    "bus_priority_link": FeatureOperatingRule("bus_priority_link", revenue_per_turn=1, upkeep_per_turn=2, decay_per_turn=4, maintenance_interval=3, maintenance_cost=8, repair_amount=45, failure_effects={"friction": 2, "activity": -1}),
    "water_main_loop": FeatureOperatingRule("water_main_loop", upkeep_per_turn=4, decay_per_turn=4, maintenance_interval=3, maintenance_cost=10, repair_amount=50, failure_effects={"exposure": 5, "friction": 1}),
    "green_buffer_reserve": FeatureOperatingRule("green_buffer_reserve", upkeep_per_turn=1, decay_per_turn=2, maintenance_interval=4, maintenance_cost=5, repair_amount=35, failure_effects={"exposure": 3, "trust": -1}),
    "affordable_infill_rezoning": FeatureOperatingRule("affordable_infill_rezoning", revenue_per_turn=3, upkeep_per_turn=2, decay_per_turn=2, maintenance_interval=4, maintenance_cost=7, repair_amount=35, failure_effects={"friction": 3, "activity": -2}),
    "construction_site": FeatureOperatingRule("construction_site", revenue_per_turn=1, upkeep_per_turn=1, lifespan_turns=2, decay_per_turn=25, failure_effects={"exposure": 3, "friction": 2}),
    "inspection_order": FeatureOperatingRule("inspection_order", upkeep_per_turn=1, lifespan_turns=1, decay_per_turn=100, failure_effects={"exposure": 2, "friction": 1}),
    "occupancy_certificate": FeatureOperatingRule("occupancy_certificate", revenue_per_turn=4, decay_per_turn=1, maintenance_interval=5, maintenance_cost=6, repair_amount=30, failure_effects={"friction": 2, "exposure": 1}),
    "vendor_sanitation_complaint": FeatureOperatingRule("vendor_sanitation_complaint", upkeep_per_turn=1, lifespan_turns=2, decay_per_turn=30, failure_effects={"friction": 3, "exposure": 2}),
    "license_fee_counter": FeatureOperatingRule("license_fee_counter", revenue_per_turn=2, lifespan_turns=2, decay_per_turn=40, failure_effects={"friction": 1}),
    "settlement_agreement": FeatureOperatingRule("settlement_agreement", revenue_per_turn=2, lifespan_turns=2, decay_per_turn=35, failure_effects={"friction": 2, "exposure": 1}),
}

VIOLATION_CODES = {
    "paperwork_gap": {"label": "Paperwork Gap", "severity": "watch"},
    "service_gap": {"label": "Service Capacity Gap", "severity": "warning"},
    "unsafe_work": {"label": "Unsafe Work Condition", "severity": "warning"},
    "public_nuisance": {"label": "Public Nuisance", "severity": "watch"},
    "maintenance_overdue": {"label": "Maintenance Overdue", "severity": "warning"},
}

INSPECTION_RULES: dict[str, InspectionRule] = {
    "default": InspectionRule("default", ("paperwork_gap", "service_gap"), ("paperwork_gap",), deadline_turns=2),
    "contractor_renovation_waiver": InspectionRule("contractor_renovation_waiver", ("paperwork_gap", "unsafe_work", "public_nuisance"), ("unsafe_work",), deadline_turns=2),
    "street_vendor_compact": InspectionRule("street_vendor_compact", ("public_nuisance", "service_gap", "paperwork_gap"), ("public_nuisance",), deadline_turns=1),
    "utility_expansion_trench": InspectionRule("utility_expansion_trench", ("service_gap", "unsafe_work"), ("unsafe_work",), deadline_turns=2),
    "fire_budget_escalation": InspectionRule("fire_budget_escalation", ("service_gap", "paperwork_gap"), ("service_gap",), deadline_turns=2),
    "business_license_fee_sweep": InspectionRule("business_license_fee_sweep", ("paperwork_gap", "public_nuisance"), ("paperwork_gap",), deadline_turns=1),
    "compliance_settlement_drive": InspectionRule("compliance_settlement_drive", ("paperwork_gap", "unsafe_work"), ("paperwork_gap",), deadline_turns=1),
    MAINTENANCE_TEMPLATE_ID: InspectionRule(MAINTENANCE_TEMPLATE_ID, ("maintenance_overdue", "service_gap"), ("maintenance_overdue",), deadline_turns=1),
}

STAKEHOLDERS: dict[str, StakeholderProfile] = {
    "general_public": StakeholderProfile("general_public", influence=2, patience=2, interests=("friction", "exposure")),
    "transit_authority": StakeholderProfile("transit_authority", influence=3, patience=3, interests=("mobility", "activity"), allies=("commuters",), rivals=("homeowners",)),
    "celebrants": StakeholderProfile("celebrants", influence=2, patience=1, interests=("trust",), allies=("artists", "vendors")),
    "utility_board": StakeholderProfile("utility_board", influence=4, patience=2, interests=("utilities", "exposure"), allies=("civil_servants",)),
    "conservation_trust": StakeholderProfile("conservation_trust", influence=3, patience=3, interests=("green_buffer", "trust"), allies=("conservationists",), rivals=("developers",)),
    "developers": StakeholderProfile("developers", influence=4, patience=1, interests=("activity", "land_use"), allies=("contractors",), rivals=("conservationists", "renters")),
    "families": StakeholderProfile("families", influence=3, patience=2, interests=("child_services", "exposure"), allies=("elders",), followup_template_id=CIVIC_INCIDENT_TEMPLATE_ID),
    "vendors": StakeholderProfile("vendors", influence=3, patience=1, interests=("activity", "culture_access"), allies=("artists",), rivals=("homeowners",)),
    "contractors": StakeholderProfile("contractors", influence=3, patience=1, interests=("activity", "inspection"), allies=("developers",)),
    "fire_department": StakeholderProfile("fire_department", influence=5, patience=2, interests=("exposure", "fire_response"), allies=("civil_servants",), escalation_threshold=3),
    "arts_council": StakeholderProfile("arts_council", influence=2, patience=3, interests=("trust",), allies=("artists", "students")),
    "maintenance_office": StakeholderProfile("maintenance_office", influence=3, patience=2, interests=("exposure", "services"), allies=("civil_servants",)),
    "public_health": StakeholderProfile("public_health", influence=4, patience=2, interests=("exposure", "vendors"), allies=("elders", "families"), followup_template_id=CIVIC_INCIDENT_TEMPLATE_ID),
    "compliance_office": StakeholderProfile("compliance_office", influence=4, patience=2, interests=("inspection", "exposure")),
    "housing_authority": StakeholderProfile("housing_authority", influence=4, patience=2, interests=("housing", "affordability"), allies=("renters", "families")),
    "renters": StakeholderProfile("renters", influence=3, patience=1, interests=("housing", "affordability"), allies=("workers", "students"), rivals=("homeowners",), followup_template_id=CIVIC_INCIDENT_TEMPLATE_ID),
    "homeowners": StakeholderProfile("homeowners", influence=3, patience=2, interests=("exposure", "friction"), rivals=("developers", "renters"), followup_template_id=CIVIC_INCIDENT_TEMPLATE_ID),
    "civil_servants": StakeholderProfile("civil_servants", influence=3, patience=2, interests=("services", "exposure"), followup_template_id=CIVIC_INCIDENT_TEMPLATE_ID),
    "workers": StakeholderProfile("workers", influence=3, patience=1, interests=("activity", "exposure"), allies=("commuters",), followup_template_id=CIVIC_INCIDENT_TEMPLATE_ID),
}

AUDIT_THRESHOLDS = {
    "service_gap_warning": 25,
    "service_gap_critical": 40,
    "feature_condition_warning": 35,
    "feature_condition_critical": 10,
}
