from __future__ import annotations

from ..models import *

TEMPLATES: dict[str, DocketTemplate] = {
    "connector_corridor": DocketTemplate(
        "connector_corridor",
        "Connector Corridor Pilot",
        "transit",
        "LINE",
        {"prosperity": 5, "risk": -2, "unrest": 2},
        {"prosperity": 2, "risk": -1, "unrest": 1},
        money_cost=24,
        mitigation_cost=10,
        preview="Improves access between two districts; the map should show a new line and a modest risk/access trade.",
        inspect_hint="Ridership math is favorable, and the alignment file has already attracted pre-appeals.",
        target_rule="Select exactly two districts to connect.",
        stakeholder="transit_authority",
        failure_mode="construction delay",
        failure_effects={"unrest": 3, "risk": 2, "prosperity": -2},
        failure_base_chance=0.22,
        good_fit_types=("mercantile", "civic"),
        bad_fit_types=("residential", "natural"),
        supporter_groups=("commuters", "workers", "developers"),
        concerned_groups=("homeowners", "elders", "conservationists"),
        growth_groups=("commuters", "workers"),
        contact_name="Deputy Alignment Officer Mira Parcel",
        spawn_archetype_id="connector_corridor",
    ),
    "procession_route": DocketTemplate(
        "procession_route",
        "Licensed Procession Route",
        "event",
        "LINE",
        {"culture": 8, "prosperity": 2, "unrest": 3, "risk": 1},
        {"culture": 2, "unrest": 1},
        money_cost=10,
        mitigation_cost=8,
        expires_after=1,
        preview="Temporary culture boost along a route; crowd-control side effects are plausible.",
        inspect_hint="Route review found enthusiasm, bottlenecks, and three mutually incompatible banner standards.",
        target_rule="Select exactly two districts for the route endpoints.",
        stakeholder="celebrants",
        denial_heat=2,
        failure_mode="crowd-control miss",
        failure_effects={"unrest": 3, "risk": 3, "culture": -1},
        failure_base_chance=0.24,
        good_fit_types=("civic", "academic", "mercantile"),
        bad_fit_types=("industrial", "natural"),
        supporter_groups=("artists", "students", "vendors"),
        concerned_groups=("commuters", "elders", "civil_servants"),
        growth_groups=("artists", "vendors"),
        contact_name="Procession Marshal Lenora Queue",
        spawn_archetype_id="licensed_procession",
    ),
    "utility_expansion_trench": DocketTemplate(
        "utility_expansion_trench",
        "Utility Expansion Trench",
        "utility",
        "LINE",
        {"risk": -6, "prosperity": 2, "unrest": 2},
        {"risk": -2, "unrest": 1},
        money_cost=22,
        mitigation_cost=8,
        preview="Reduces infrastructure risk; the line work should visibly steady industrial service coverage.",
        inspect_hint="Utility maps agree on the pipe location except where the pipe is most important.",
        target_rule="Select exactly two districts crossed by the utility work.",
        stakeholder="utility_board",
        ignore_heat=2,
        failure_mode="service outage",
        failure_effects={"risk": 5, "unrest": 2, "prosperity": -1},
        failure_base_chance=0.25,
        good_fit_types=("industrial", "civic"),
        bad_fit_types=("residential", "natural"),
        supporter_groups=("families", "workers", "civil_servants"),
        concerned_groups=("commuters", "vendors", "homeowners"),
        growth_groups=("workers",),
        contact_name="Utilities Cartographer Oren Plumb",
        spawn_archetype_id="utility_trench",
    ),
    "natural_reserve_conversion": DocketTemplate(
        "natural_reserve_conversion",
        "Natural Reserve Conversion",
        "land",
        "POLYGON",
        {"culture": 5, "risk": -4, "prosperity": -2, "unrest": 1},
        {"culture": 2, "risk": -1, "prosperity": -1},
        money_cost=12,
        mitigation_cost=5,
        preview="Creates a protected polygon, lowers hazard pressure, and gives the audit a visible green-buffer answer.",
        inspect_hint="Boundary markers are persuasive, except one that appears to have legal opinions.",
        target_rule="Select one or more districts proposed for reserve status.",
        stakeholder="conservation_trust",
        denial_heat=2,
        failure_mode="boundary dispute",
        failure_effects={"unrest": 3, "risk": 2, "culture": -2},
        failure_base_chance=0.20,
        good_fit_types=("natural", "academic"),
        bad_fit_types=("industrial", "mercantile"),
        supporter_groups=("conservationists", "artists", "elders"),
        concerned_groups=("developers", "workers", "commuters"),
        growth_groups=("conservationists",),
        decline_groups=("developers",),
        contact_name="Boundary Steward Iva Reed",
        spawn_archetype_id="protected_reserve",
    ),
    "mixed_use_rezoning": DocketTemplate(
        "mixed_use_rezoning",
        "Mixed-Use Rezoning Petition",
        "development",
        "POLYGON",
        {"prosperity": 6, "unrest": 3, "risk": 2, "culture": 1},
        {"prosperity": 2, "unrest": 1},
        money_cost=16,
        mitigation_cost=9,
        preview="Adds growth pressure and tax base; neighborhood fit and service capacity are uncertain.",
        inspect_hint="Applicant submitted renderings with people smiling near loading docks.",
        target_rule="Select one or more districts to rezone.",
        stakeholder="developers",
        denial_heat=2,
        failure_mode="zoning appeal",
        failure_effects={"unrest": 4, "risk": 1, "prosperity": -2},
        failure_base_chance=0.23,
        good_fit_types=("residential", "mercantile"),
        bad_fit_types=("natural", "civic"),
        supporter_groups=("developers", "workers", "commuters"),
        concerned_groups=("renters", "homeowners", "conservationists"),
        growth_groups=("renters", "workers", "commuters"),
        decline_groups=("conservationists",),
        contact_name="Petitioner Bram Floorplate",
        spawn_archetype_id="mixed_use_overlay",
    ),
    "child_development_park_annex": DocketTemplate(
        "child_development_park_annex",
        "Child Development Park Annex",
        "education",
        "POINT",
        {"culture": 5, "risk": -3, "unrest": -1, "prosperity": 1},
        {"culture": 1, "risk": -1},
        money_cost=18,
        mitigation_cost=6,
        preview="Adds a point-service annex for families; the report should show child-service and risk relief.",
        inspect_hint="Need is clear; staffing plan depends on a committee that has named itself provisional twice.",
        target_rule="Select exactly one district for the annex.",
        stakeholder="families",
        denial_heat=2,
        failure_mode="staffing shortfall",
        failure_effects={"risk": 3, "unrest": 2, "culture": -1},
        failure_base_chance=0.18,
        good_fit_types=("residential", "academic", "civic"),
        bad_fit_types=("industrial",),
        supporter_groups=("families", "elders", "civil_servants"),
        concerned_groups=("commuters", "homeowners"),
        growth_groups=("families",),
        contact_name="Acting Recreation Notary June Totlot",
        spawn_archetype_id="child_service_annex",
    ),
    "street_vendor_compact": DocketTemplate(
        "street_vendor_compact",
        "Street Vendor Compact",
        "business",
        "POINT",
        {"prosperity": 6, "culture": 4, "unrest": 2, "risk": 1},
        {"prosperity": 2, "culture": 1, "unrest": 1},
        money_cost=12,
        mitigation_cost=6,
        preview="Creates a visible small-commerce point; useful for showing mitigation before nuisance issues spread.",
        inspect_hint="Public comments mention foot traffic, late music, and unusually precise snack zoning.",
        target_rule="Select exactly one host district.",
        stakeholder="vendors",
        denial_heat=2,
        ignore_heat=2,
        failure_mode="unlicensed spillover",
        failure_effects={"unrest": 3, "risk": 2, "prosperity": -1},
        failure_base_chance=0.22,
        good_fit_types=("mercantile", "residential"),
        bad_fit_types=("civic", "natural"),
        supporter_groups=("vendors", "artists", "students"),
        concerned_groups=("homeowners", "civil_servants", "commuters"),
        growth_groups=("vendors", "artists"),
        contact_name="Compact Spokesperson Della Cart",
        spawn_archetype_id="vendor_market",
    ),
    "contractor_renovation_waiver": DocketTemplate(
        "contractor_renovation_waiver",
        "Contractor Renovation Waiver",
        "residential",
        "POINT",
        {"prosperity": 4, "risk": 3, "unrest": 1},
        {"unrest": 1, "risk": 1},
        money_cost=14,
        mitigation_cost=7,
        preview="Speeds a residential project; contractor reliability and inspection burden are only partly knowable.",
        inspect_hint="The contractor has completed many jobs, several of which are admired from a distance.",
        target_rule="Select exactly one district containing the work.",
        stakeholder="contractors",
        ignore_heat=2,
        failure_mode="inspection failure",
        failure_effects={"risk": 6, "unrest": 2, "prosperity": -2},
        failure_base_chance=0.28,
        good_fit_types=("residential", "mercantile"),
        bad_fit_types=("natural", "academic"),
        supporter_groups=("homeowners", "developers", "workers"),
        concerned_groups=("renters", "elders"),
        growth_groups=("homeowners", "developers"),
        decline_groups=("renters",),
        contact_name="Licensed Expediter Hal Permit",
        spawn_archetype_id="renovation_site",
    ),
    "fire_budget_escalation": DocketTemplate(
        "fire_budget_escalation",
        "Fire Department Budget Escalation",
        "department",
        "POLYGON",
        {"risk": -7, "unrest": -1, "prosperity": -2},
        {"risk": -2},
        money_cost=20,
        mitigation_cost=5,
        preview="Adds a coverage polygon that lowers fire and risk exposure; denial leaves a clean audit contrast.",
        inspect_hint="The department's incident trend is real; the proposed equipment list includes ceremonial ladders.",
        target_rule="Select one or more districts covered by the budget request.",
        stakeholder="fire_department",
        denial_heat=3,
        ignore_heat=2,
        failure_mode="coverage gap",
        failure_effects={"risk": 4, "unrest": 2},
        failure_base_chance=0.16,
        good_fit_types=("industrial", "civic", "residential"),
        bad_fit_types=("natural",),
        supporter_groups=("civil_servants", "families", "workers"),
        concerned_groups=("developers", "conservationists"),
        growth_groups=("civil_servants",),
        contact_name="Battalion Budget Clerk Rhea Ladder",
        spawn_archetype_id="fire_coverage_area",
    ),
    "public_art_museum_grant": DocketTemplate(
        "public_art_museum_grant",
        "Public Art and Museum Grant",
        "culture",
        "POINT",
        {"culture": 7, "prosperity": 1, "unrest": 1},
        {"culture": 2},
        money_cost=15,
        mitigation_cost=6,
        preview="Raises cultural profile; controversy risk is filed under community interpretation.",
        inspect_hint="The museum board is solvent, passionate, and unable to agree on the word temporary.",
        target_rule="Select exactly one district for the grant site.",
        stakeholder="arts_council",
        failure_mode="procurement scandal",
        failure_effects={"unrest": 3, "culture": -3, "prosperity": -1},
        failure_base_chance=0.20,
        good_fit_types=("civic", "academic", "mercantile"),
        bad_fit_types=("industrial",),
        supporter_groups=("artists", "students", "vendors"),
        concerned_groups=("civil_servants", "homeowners"),
        growth_groups=("artists", "students"),
        contact_name="Museum Board Chair Sable Plinth",
        spawn_archetype_id="museum_grant_site",
    ),
    ENFORCEMENT_TEMPLATE_ID: DocketTemplate(
        ENFORCEMENT_TEMPLATE_ID,
        "Unpermitted Follow-Through",
        "enforcement",
        "POINT",
        {"risk": -3, "unrest": 2, "prosperity": -1},
        {"unrest": 1},
        money_cost=8,
        mitigation_cost=6,
        preview="A previously rejected or ignored request appears to have proceeded in practical terms.",
        inspect_hint="Compliance photos are persuasive but timestamped with civic optimism.",
        target_rule="Select exactly one district where the unpermitted work or event is visible.",
        stakeholder="general_public",
        denial_heat=2,
        ignore_heat=2,
        is_enforcement=True,
        supporter_groups=("civil_servants", "homeowners"),
        concerned_groups=("vendors", "renters", "workers"),
        contact_name="Compliance Inspector Niko Ledger",
        spawn_archetype_id="compliance_case",
    ),
    CIVIC_INCIDENT_TEMPLATE_ID: DocketTemplate(
        CIVIC_INCIDENT_TEMPLATE_ID,
        "Civic Incident Response",
        "incident",
        "POINT",
        {"unrest": -2, "risk": -1, "prosperity": -1},
        {"unrest": -1},
        money_cost=9,
        mitigation_cost=7,
        preview="A local grievance has become administratively visible and requests a response before it becomes policy.",
        inspect_hint="Complaint packet includes signatures, two maps, and a folder labeled previous folder.",
        target_rule="Select exactly one district where the civic incident is visible.",
        stakeholder="general_public",
        denial_heat=1,
        ignore_heat=2,
        is_incident=True,
        supporter_groups=("civil_servants",),
        concerned_groups=("families", "workers", "renters", "vendors"),
        contact_name="Incident Intake Coordinator Vera Stamp",
        spawn_archetype_id="civic_incident_marker",
    ),
    "bus_priority_link": DocketTemplate(
        "bus_priority_link",
        "Bus Priority Link",
        "transit",
        "LINE",
        {"prosperity": 3, "risk": -1, "unrest": 1},
        {"prosperity": 1, "risk": -1},
        money_cost=18,
        mitigation_cost=6,
        preview="Adds a bus-priority segment; curb access objections are likely but mobility math is favorable.",
        inspect_hint="Transit staff can explain the signal priority but not the diagram colors.",
        target_rule="Select exactly two districts for link endpoints.",
        stakeholder="transit_authority",
        failure_mode="curb-management dispute",
        failure_effects={"unrest": 2, "prosperity": -1},
        failure_base_chance=0.16,
        good_fit_types=("mercantile", "civic", "academic"),
        bad_fit_types=("natural",),
        supporter_groups=("commuters", "workers", "students"),
        concerned_groups=("homeowners", "vendors"),
        growth_groups=("commuters", "workers"),
        contact_name="Signal Priority Clerk Asa Lane",
        spawn_archetype_id="bus_priority_link",
        scenario_tags=("port_boom",),
    ),
    "water_main_loop": DocketTemplate(
        "water_main_loop",
        "Water Main Loop",
        "utility",
        "LINE",
        {"risk": -5, "prosperity": 1, "unrest": 1},
        {"risk": -2},
        money_cost=24,
        mitigation_cost=8,
        preview="Loops water service between districts; it lowers flood and fire fragility if the trenching behaves.",
        inspect_hint="Hydraulic notes are clean, and every clean note has a page two.",
        target_rule="Select exactly two districts for the loop endpoints.",
        stakeholder="utility_board",
        failure_mode="valve coordination miss",
        failure_effects={"risk": 4, "unrest": 2},
        failure_base_chance=0.18,
        good_fit_types=("industrial", "civic", "residential"),
        bad_fit_types=("natural",),
        supporter_groups=("families", "workers", "civil_servants"),
        concerned_groups=("commuters", "homeowners"),
        growth_groups=("workers",),
        contact_name="Loop Engineer Mara Gauge",
        spawn_archetype_id="water_main_loop",
        scenario_tags=("port_boom",),
    ),
    "green_buffer_reserve": DocketTemplate(
        "green_buffer_reserve",
        "Green Buffer Reserve",
        "land",
        "POLYGON",
        {"culture": 4, "risk": -4, "prosperity": -1},
        {"culture": 1, "risk": -1},
        money_cost=14,
        mitigation_cost=5,
        preview="Creates a planted buffer that absorbs heat, noise, and ecological pressure.",
        inspect_hint="Planting plan is plausible; maintenance plan is written in future tense.",
        target_rule="Select one or more districts for the reserve boundary.",
        stakeholder="conservation_trust",
        failure_mode="maintenance shortfall",
        failure_effects={"risk": 2, "unrest": 1, "culture": -1},
        failure_base_chance=0.14,
        good_fit_types=("natural", "residential", "academic"),
        bad_fit_types=("industrial",),
        supporter_groups=("conservationists", "families", "elders", "artists"),
        concerned_groups=("developers", "workers"),
        growth_groups=("conservationists", "artists"),
        decline_groups=("developers",),
        contact_name="Buffer Steward Nela Canopy",
        spawn_archetype_id="green_buffer_reserve",
        scenario_tags=("garden_city",),
    ),
    "inspection_order": DocketTemplate(
        "inspection_order",
        "Inspection Order",
        "compliance",
        "POINT",
        {"risk": -3, "unrest": 1},
        {"risk": -1},
        money_cost=8,
        mitigation_cost=4,
        preview="Orders a compliance inspection; pollution, fire, and noise risks can drop after paperwork becomes physical.",
        inspect_hint="The inspector is available, which is a rare and meaningful sentence.",
        target_rule="Select exactly one district for the inspection order.",
        stakeholder="compliance_office",
        failure_mode="missed inspection window",
        failure_effects={"risk": 2, "unrest": 1},
        failure_base_chance=0.12,
        supporter_groups=("families", "elders", "civil_servants"),
        concerned_groups=("vendors", "developers", "workers"),
        contact_name="Inspector Sol Form",
        spawn_archetype_id="inspection_order",
    ),
    "affordable_infill_rezoning": DocketTemplate(
        "affordable_infill_rezoning",
        "Affordable Infill Rezoning",
        "development",
        "POLYGON",
        {"prosperity": 3, "unrest": 2, "risk": 1, "culture": 1},
        {"prosperity": 1, "unrest": 1},
        money_cost=18,
        mitigation_cost=9,
        preview="Starts an affordable infill buildout; capacity arrives only after construction, inspection, and occupancy.",
        inspect_hint="The covenant packet is legible, which makes everyone suspicious in a useful way.",
        target_rule="Select one or more districts to rezone for affordable infill.",
        stakeholder="housing_authority",
        denial_heat=2,
        failure_mode="zoning appeal",
        failure_effects={"unrest": 4, "risk": 1, "prosperity": -1},
        failure_base_chance=0.20,
        housing_effects={"affordability": 4},
        starts_chain_id="affordable_infill_buildout",
        project_step_id="rezoning",
        good_fit_types=("residential", "mercantile"),
        bad_fit_types=("natural", "industrial"),
        supporter_groups=("renters", "families", "workers", "developers"),
        concerned_groups=("homeowners", "commuters"),
        growth_groups=("renters", "families", "workers"),
        decline_groups=("homeowners",),
        contact_name="Housing Planner Mina Ledger",
        spawn_archetype_id="affordable_infill_rezoning",
        scenario_tags=("housing_mandate",),
    ),
    "infill_construction_site": DocketTemplate(
        "infill_construction_site",
        "Infill Construction Mobilization",
        "development",
        "POINT",
        {"prosperity": 2, "unrest": 2, "risk": 2},
        {"unrest": 1, "risk": 1},
        money_cost=16,
        mitigation_cost=8,
        expires_after=2,
        preview="Mobilizes the approved infill site; temporary noise and fire exposure enter the ledger.",
        inspect_hint="Construction schedule is complete except for the part involving weather and subcontractors.",
        target_rule="Select exactly one district inside the approved infill project.",
        stakeholder="housing_authority",
        failure_mode="construction safety violation",
        failure_effects={"risk": 5, "unrest": 2, "prosperity": -1},
        failure_base_chance=0.24,
        hazard_effects={"noise": 1, "fire": 1},
        project_step_id="construction",
        supporter_groups=("developers", "workers", "renters"),
        concerned_groups=("elders", "homeowners", "families"),
        growth_groups=("workers", "developers"),
        contact_name="Site Coordinator Pavi Brace",
        spawn_archetype_id="construction_site",
        scenario_tags=("housing_mandate",),
    ),
    "infill_inspection_order": DocketTemplate(
        "infill_inspection_order",
        "Infill Final Inspection",
        "compliance",
        "POINT",
        {"risk": -4, "unrest": -1},
        {"risk": -1},
        money_cost=9,
        mitigation_cost=5,
        preview="Runs the final inspection that clears or stalls the infill project.",
        inspect_hint="The checklist has boxes, and several boxes have opinions.",
        target_rule="Select exactly one district containing the infill project.",
        stakeholder="compliance_office",
        failure_mode="failed inspection",
        failure_effects={"risk": 4, "unrest": 3, "prosperity": -1},
        failure_base_chance=0.22,
        project_step_id="inspection",
        supporter_groups=("families", "renters", "civil_servants"),
        concerned_groups=("developers", "workers"),
        contact_name="Final Inspector Theo Stamp",
        spawn_archetype_id="inspection_order",
        scenario_tags=("housing_mandate",),
    ),
    "occupancy_certificate": DocketTemplate(
        "occupancy_certificate",
        "Occupancy Certificate",
        "compliance",
        "POINT",
        {"prosperity": 2, "culture": 1, "risk": -1},
        {"prosperity": 1},
        money_cost=7,
        mitigation_cost=4,
        preview="Certifies occupancy; housing capacity and population become real enough to complain about services.",
        inspect_hint="Addressing is complete, and that is more dramatic than expected.",
        target_rule="Select exactly one district receiving occupancy.",
        stakeholder="housing_authority",
        failure_mode="delayed occupancy",
        failure_effects={"unrest": 2, "risk": 1, "prosperity": -1},
        failure_base_chance=0.12,
        housing_effects={"housing_capacity": 420, "population": 180, "affordability": 6},
        project_step_id="occupancy",
        supporter_groups=("renters", "families", "workers"),
        concerned_groups=("commuters", "homeowners"),
        growth_groups=("renters", "families", "workers"),
        contact_name="Occupancy Clerk Neve Key",
        spawn_archetype_id="occupancy_certificate",
        scenario_tags=("housing_mandate",),
    ),
    "vendor_sanitation_complaint": DocketTemplate(
        "vendor_sanitation_complaint",
        "Vendor Sanitation Complaint",
        "incident",
        "POINT",
        {"unrest": -1, "risk": -2, "prosperity": -1},
        {"unrest": -1},
        money_cost=7,
        mitigation_cost=5,
        preview="A vendor-market nuisance file has matured into a sanitation complaint.",
        inspect_hint="Complaint photos show queues, wrappers, and one very organized clipboard.",
        target_rule="Select exactly one district hosting the vendor market.",
        stakeholder="public_health",
        denial_heat=2,
        ignore_heat=2,
        failure_mode="complaint escalation",
        failure_effects={"unrest": 3, "risk": 2},
        failure_base_chance=0.18,
        project_step_id="vendor_complaint",
        is_incident=True,
        supporter_groups=("families", "elders", "civil_servants"),
        concerned_groups=("vendors", "artists", "students"),
        contact_name="Sanitation Intake Lead Ora Carton",
        spawn_archetype_id="vendor_sanitation_complaint",
    ),
}

TEMPLATES[MAINTENANCE_TEMPLATE_ID] = DocketTemplate(
    MAINTENANCE_TEMPLATE_ID,
    "Feature Maintenance Order",
    "maintenance",
    "POINT",
    {"risk": -1, "unrest": -1},
    {},
    money_cost=6,
    mitigation_cost=4,
    preview="An active support feature is due for maintenance; approve it to show a generated follow-up resolving cleanly.",
    inspect_hint="The maintenance ledger is concise, which is how it signals danger.",
    target_rule="Select the affected district or process the referenced support feature.",
    stakeholder="maintenance_office",
    denial_heat=1,
    ignore_heat=1,
    failure_mode="deferred maintenance",
    failure_effects={"risk": 2, "unrest": 1},
    failure_base_chance=0.08,
    is_enforcement=True,
    supporter_groups=("civil_servants", "families", "workers"),
    concerned_groups=("developers", "vendors"),
    contact_name="Maintenance Clerk Sera Wrench",
    spawn_archetype_id="compliance_case",
)

DEMO_TEMPLATE_IDS = (
    "connector_corridor",
    "procession_route",
    "utility_expansion_trench",
    "natural_reserve_conversion",
    "mixed_use_rezoning",
    "child_development_park_annex",
    "street_vendor_compact",
    "contractor_renovation_waiver",
    "fire_budget_escalation",
    "public_art_museum_grant",
)

DEMO_SEQUENCE = {
    1: ("connector_corridor", "procession_route", "street_vendor_compact"),
    2: ("utility_expansion_trench", "contractor_renovation_waiver", "public_art_museum_grant"),
    3: ("natural_reserve_conversion", "mixed_use_rezoning", "fire_budget_escalation"),
    4: ("child_development_park_annex", "street_vendor_compact", "utility_expansion_trench"),
    5: ("connector_corridor", "mixed_use_rezoning", "public_art_museum_grant"),
    6: ("natural_reserve_conversion", "fire_budget_escalation", "procession_route"),
}

